### PR TITLE
Map page massive upgrade

### PR DESCRIPTION
**Pull request by prajankya**

### CODE REVIEW

**Comment by prajankya** [comment]
Just added preloader, still not added  markers yet.

**Comment by prajankya** [comment]
@DLu  can I move the data from yaml to json?

As it has many advantages over the current yaml,

- KML layer is not necessary and can just be made with markers.
- If KML is not required then generate_kml.py is also not required.
- Also yaml by itself would need conversion library, so json would be better.
- As JSON is a bit better tolerable to indentations, it is lesser prone to creating problems in PRs, hence no Linter required.

**Comment by prajankya** [comment]
@DLu few other queries,

Do you need to have that Pie chart ? I was planning on putting check-boxes in the legend of the map, which can be selected to show or hide that type.

Also, I have addressed #95 any other things you wish to address?

**Comment by prajankya** [comment]
you can check the current map at [https://prajankya.github.io/ros_map/map.html](https://prajankya.github.io/ros_map/map.html) before merging

**Comment by prajankya** [comment]
Had to add API key for the https://prajankya.github.io/ros_map/map.html to work,

so added an API key with limits of referrer, so only two domains can use that API key,

prajankya.github.io and metrorobots.com

of which first one is just temporary for to check the current status of the upgrade.

**Comment by prajankya** [comment]
You can check the Map at https://prajankya.github.io/ros_map/map.html 

I have moved from yaml to json, hope you consider what I have done. Any suggestions greatly appreciated.

**Comment by prajankya** [comment]
@DLu I have done how much I have thought, if any ideas or changes please tell. Hope you like it, if its too much UI(I am feeling like it) just tell..

**Comment by prajankya** [comment]
@DLu can you me tell if anything is wrong with this PR?

**Comment by DLu** [comment]
@prajankya My sincere apologies for ignoring this for so long. Right as you sent it to me was right around when I had my first kid, and that has been distracting me for the past few months. 

I really appreciate you putting some much-needed love into this repo, but right now, there's a bit too much going on in this one pull request. Would you be willing to break this up into a few smaller PRs with clear descriptions of what the new features are?

**Comment by prajankya** [comment]
Sure, Will do..!


and congrats for your first kid !!

**Comment by prajankya** [comment]
Can you just check out the link https://prajankya.github.io/ros_map/map.html as I frankly am not a UI designer, and hence am not confident upon whether the community would like it. If any suggestions, please tell me..

**Comment by DLu** [comment]
On the whole, I think it is a nice interace. My major complaint is that it doesn't show all of the points when zoomed out. There's a tradeoff between showing too much and too little, but one of the cool things about the ROS users map is being able to take a quick glance and say "wow there's a lot of ROS users."

**Comment by prajankya** [comment]
Sure, will do.!! I agree on your point of view. I am a bit pre-occupied, but I'lll soon start on this one..

**Comment by DLu** [comment]
Closing for now.

**Pull request closed without merging**
